apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: monitoring
data:
  prometheus.rules: |
    # Define your alert rules here
    groups:
    - name: example
      rules:
      - alert: HighPodCpuUsage
        expr: sum(rate(container_cpu_usage_seconds_total{container!="POD",pod!="",namespace!="kube-system"}[5m])) by (pod) / sum(kube_pod_container_resource_limits_cpu_cores{container!="POD",pod!="",namespace!="kube-system"})
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: High CPU usage in pods
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'kubernetes-apiservers'
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https
    # Define other scrape jobs here
