apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 5Gi   
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  nfs:
    server: 192.168.1.101
    path: /mnt/data
